### ISSUE TITLE
Bug of function predict with a customCollection

### ISSUE THREAD

**Issue by HamzaApache** [IndicoDataSolutions/IndicoIo-Java#79]
Hi, I encountered a bug using the predict function with a customCollection.
I noticed that the bug occurs on strings containing 4 characters.
My java code that causes the bug is:

	Indico indico = new Indico(theKey);
	IndicoCollection sentimentCollection = indico.custom.getCollection(MyCollectionName);
	sentimentCollection.predict("test");

And the trace of the bug is:
	
	Exception in thread "main" java.lang.NullPointerException
	at io.indico.api.utils.ImageUtils.resize(ImageUtils.java:125)
	at io.indico.api.utils.ImageUtils.handleImage(ImageUtils.java:97)
	at io.indico.api.utils.ImageUtils.handleString(ImageUtils.java:119)
	at io.indico.api.utils.ImageUtils.convertToImage(ImageUtils.java:62)
	at io.indico.api.custom.IndicoCollection.predict(IndicoCollection.java:132)
	at controller.TagsValidationController.main(TagsValidationController.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

I would be grateful if you could give me a solution to this.

**Comment by sihrc** [comment]
It appears that our data preprocessing logic needs to be updated. Sit tight for a patch!
